FROM oven/bun:latest
WORKDIR /usr/src/app

ARG DISCORD_TOKEN=${THRESHOLD}
ENV DISCORD_TOKEN=${THRESHOLD}

ARG ENABLED=${ENABLED}
ENV ENABLED=${ENABLED}

ARG DATABASE_URL=${DATABASE_URL}
ENV DATABASE_URL=${DATABASE_URL}

ARG REDIS_URL=${REDIS_URL}
ENV REDIS_URL=${REDIS_URL}

COPY bun.lockb package.json prisma ./
RUN bun install

COPY . .
RUN bunx prisma generate

ENV NODE_ENV production

EXPOSE 3000
ENTRYPOINT [ "bun", "dev" ]